quarkus:
  application:
    name: home-library-catalog
  http:
    port: 8080
    cors: 
      origins: "*"
      methods: "GET,POST,PUT,DELETE,PATCH"
      headers: "Content-Type, Accept, X-Requested-With, remember-me"
      access-control-max-age: "3600"
      access-control-allow-credentials: true
  log:
    level: INFO
    console:
      enable: true
